FROM node:14.20 AS build

RUN mkdir -p /usr/src/sqream
RUN mkdir -p /usr/src/sqream/client

WORKDIR /usr/src/sqream/client

COPY ./package.json /usr/src/sqream/client

RUN npm install && npm cache clean --force

WORKDIR /usr/src/sqream/client

COPY ./ /usr/src/sqream/client/

RUN npm install

RUN npm run build 

FROM nginx:latest AS ngi
COPY --from=build /usr/src/sqream/client/dist/client /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
