FROM node:14.18.3 as base

RUN mkdir -p /usr/src/sqream
RUN mkdir -p /usr/src/sqream/server

WORKDIR /usr/src/sqream/sq-server

COPY ./package.json /usr/src/sqream/server

RUN npm install && npm cache clean --force

WORKDIR /usr/src/sqream/server

COPY ./ /usr/src/sqream/server/

RUN npm install

EXPOSE 4000


CMD ["npm", "run", "start"]